#
#
version: '3.1'
#
services:
  spark-master:
    image: spark:3.0.1-3.2.0
    container_name: spark-master
    hostname: spark-master
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - /e/apps/hostpath/spark:/e/apps/hostpath/spark  
    environment:
      NODE_TYPE: MASTER
      WEBUI_PORT: 8080
#
  spark-node01:
    image: spark:3.0.1-3.2.0
    container_name: spark-node01
    hostname: spark-node01
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    volumes:
      - /e/apps/hostpath/spark:/e/apps/hostpath/spark  
    environment:
      NODE_TYPE: WORKER
      WEBUI_PORT: 8081
#

#      
  namenode:
    image: hadoop:3.2.0-single
    container_name: namenode
    ports:
      - "9000:9000"
      - "9866:9866"  
      - "9870:9870"
      - "9864:9864" 
    command: /usr/local/bin/start-namenode.sh
    hostname: namenode
    volumes:
      - /e/apps/hostpath/spark/data:/data
      - /e/apps/hostpath/spark/in:/in
      
#
#  spark-node02:
#    image: spark:3.0.1-3.2.0
#    container_name: spark-node02
#    hostname: spark-node02
#    depends_on:
#      - spark-master
#    ports:
#      - 8082:8082
#    volumes:
#      - /e/apps/hostpath/spark:/e/apps/hostpath/spark  
#    environment:
#      NODE_TYPE: WORKER
#      WEBUI_PORT: 8082
#

  history-server:
    image: spark:3.0.1-3.2.0
    container_name: history-server
    hostname: history-server
    depends_on:
      - spark-master
    ports:
      - 18080:18080
    volumes:
      - /e/apps/hostpath/spark:/e/apps/hostpath/spark  
    environment:
      NODE_TYPE: LOGSERVER

#
#networks:
#  default:
#    external:
#      name: bridge  
#  backend:
#    driver: bridge
# 