#
#
#
version: '3.1'
#
services:
#
  hive:
    image: hadoop:3.2.0
    container_name: hive
    hostname: hiveserver
    command: /usr/local/bin/start-hive.sh
    volumes:
      - /e/apps/hostpath/hive:/user/hive
    environment:
      DATA_DIR: /user/hive/warehouse
    ports:
      - 10000:10000
      - 9083:9083     